'use client'

import { redirect } from 'next/navigation'
import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.css';
import { Noto_Sans } from 'next/font/google';
import { useEffect, useState } from 'react';

const not = Noto_Sans({ subsets: ['latin'] });

/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};*/

export default function RootLayout({ children }) {
  const [isHomePage, setIsHomePage] = useState(false);

  useEffect(() => {
    const currentPath = window.location.pathname;
    setIsHomePage(currentPath === '/');

    if (currentPath !== '/' && isHomePage) {
      redirect('/');
    }
  }, [isHomePage]);


  return (
    <html lang="en">
      <body className={not.className}>
        {isHomePage ? null : <Navbar />}
        {children}
        <Footer />
      </body>
    </html>
  );
}
